### ISSUE TITLE
Hyper not starting after reboot or sleep

### ISSUE THREAD

**Issue by avxkim** [Favna/hyper-overlay#4]
If i reboot or put PC to sleep, then wake it up, i can't call Hyper visor with a hotkey, i need to start the app first.

**Comment by favna** [comment]
I don't know about Hyper Visor since that's a whole other plugin [found here](https://github.com/CWSpear/hyperterm-visor) and it is made for Hyperterm which is the v1.x version of the terminal whereas v2.x is just called `Hyper`. 

As for rebooting, that makes sense. Plugins like hyper-overlay and hyperterm-visor rely on hyper having been executed at least once since they are **plugins** not **program**. 

As for sleeping, I cannot reproduce this. When I put my (Win10) PC to sleep, wake it up again then unlock it Hyper is still there. What version of Hyper are you using? The latest stable is [v2.0.0](https://github.com/zeit/hyper/releases/tag/2.0.0)

**Comment by avxkim** [comment]
I mean your plugin, sorry, hyper overlay.

i have `startup: true` in .hyper.js, but seems like it's not working?

I am using latest stable 2.0.0, try to leave your pc at sleep state overnight

**Comment by favna** [comment]
I remain at not being able to reproduce this. Whenever I wake my PC after extended sleep the Hyper window will still be there and so will the plugin. Likewise if I close Hyper then put it to sleep the overlay will still be in my tray and summoned on hotkey.

**Comment by avxkim** [comment]
Are you using WSL Bash? Or just windows PS/CMD?

**Comment by favna** [comment]
I have my Hyper set to Git Bash as shell. [here is my config](https://hastebin.com/yanodoqoma.js)

**Comment by avxkim** [comment]
I'm using WSL Bash. Try it :)

**Comment by favna** [comment]
Sorry, no. I'm not going to install WSL and reconfigure my Hyper just for this niche plugin and to debug something. If you want to debug it and resolve the code then by all means do and make a PR but I'm not going to jump through that many hoops for this.

**Comment by jcklpe** [comment]
I'm having a similar problem @Favna and I'm also using WSL. 

Also I don't think Heihachi88 was trying to make you jump through any hoops, it's just WSL is really powerful and I think they meant the suggestion in good spirits :)

**Comment by favna** [comment]
I have no doubts that WSL is very powerful however I remain at what I said before. That said, if you want to debug and potentially resolve it yourself you are totally free to PR it and I'll be sure to accept it.
